version: '3.7'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    entrypoint: "mitmweb --web-host 0.0.0.0 --mode transparent -s /redirect-to-fabio.py"
    volumes:
      - ./redirect-to-fabio.py:/redirect-to-fabio.py
    networks:
      - app-network
    ports:
      - '8083:8081'
      - '9999:8080'

  consul:
    image: consul
    networks:
      - app-network
    ports:
      - "8500:8500"
      - "8300:8300"

  registrator:
    command: consul://127.0.0.1:8500
    image: gliderlabs/registrator:v6
    network_mode: host
    depends_on:
      - consul
      - fabio
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  fabio:
    image: fabiolb/fabio
    depends_on:
      - consul
    ports:
      # - "9999:9999"
      - "9998:9998"
    networks:
      - app-network
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500

  docker-gs:
    image: docker/getting-started
    ports:
      - "8091:80"
    networks:
      - app-network
    environment:
      - SERVICE_TAGS=urlprefix-/
      - SERVICE_80_CHECK_HTTP=/
      - SERVICE_80_CHECK_INTERVAL=10s

  nginx:
    image: nginx
    ports:
      - "8093:80"
    networks:
      - app-network
    environment:
      - SERVICE_TAGS=urlprefix-/nginx strip=/nginx
      - SERVICE_80_CHECK_HTTP=/
      - SERVICE_80_CHECK_INTERVAL=10s

networks:
  app-network: