version: '3.7'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300:8300"
    networks:
      - app-network

  registrator:
    command: consul://consul:8500
    image: gliderlabs/registrator
    depends_on:
      - consul
      - fabio
      - web
    networks:
      - app-network
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  fabio:
    image: fabiolb/fabio
    depends_on:
      - consul
    ports:
      - "9999:9999"
      - "9998:9998"
    networks:
      - app-network
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
  web:
    image: web-server
    build:
      context: .
      dockerfile: node-server/Dockerfile
    ports:
      - "8080:3000"
    networks:
      - app-network
    environment:
      - SERVICE_TAGS=urlprefix-/web
      - SERVICE_3000_CHECK_HTTP=/web
      - SERVICE_3000_CHECK_INTERVAL=10s

networks:
  app-network: