version: '3.7'
services:
  consul:
    image: consul
    networks:
      - app-network
    ports:
      - "8500:8500"
      - "8300:8300"

  registrator:
    command: consul://127.0.0.1:8500
    image: gliderlabs/registrator:v6
    network_mode: host
    depends_on:
      - consul
      - fabio
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  fabio:
    image: fabiolb/fabio
    depends_on:
      - consul
    ports:
      - "9999:9999"
      - "9998:9998"
    networks:
      - app-network
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500

  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - "8070:3000"
    networks:
      - app-network
    environment:
      - SERVICE_TAGS=urlprefix-/
      - SERVICE_3000_CHECK_HTTP=/
      - SERVICE_3000_CHECK_INTERVAL=10s

  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    entrypoint: "mitmweb --web-host 0.0.0.0"
    networks:
      - app-network
    ports:
      - '8083:8081'

networks:
  app-network: